I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 188, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 188, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\DenizSenkarabacak\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\DenizSenkarabacak\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\DenizSenkarabacak\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
soundgame 1.0
Mon Apr 29 23:51:04 2024
